# Generated by Django 3.1.6 on 2021-07-26 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20210722_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=1000)),
                ('amount_pay', models.DecimalField(decimal_places=2, max_digits=40)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='direccion',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='ciudad',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='pais',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='telefono',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=40)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('gender', models.CharField(max_length=8)),
                ('active', models.BooleanField(default=True)),
                ('amount', models.IntegerField(max_length=1000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductsCategories', to='shopping.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductsCreate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(max_length=50)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductOrders', to='shopping.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Orders', to='shopping.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomerOrders', to=settings.AUTH_USER_MODEL),
        ),
    ]
