# Generated by Django 3.1.6 on 2021-07-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_auto_20210726_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
