# Generated by Django 3.1.6 on 2021-08-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_product_cart_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cart_by',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='products_buy', to='shopping.Product'),
        ),
        migrations.DeleteModel(
            name='OrderDetails',
        ),
    ]
